- hosts: client
  become: yes
  gather_facts: no
  tasks:
  
  - name: install packages
    package: 
      name:
        - make
        - iperf
        - golang-go
        - nodejs 
        - npm
      state: present
  
#   - name: Download 
#     get_url:
#       url: https://raw.githubusercontent.com/QCDIS/blockchain_deplyment/master/install-caliper.sh
#       dest: /tmp/install-caliper.sh
#       mode: '777'
  
#   - name: install 
#     shell: bash /tmp/install-caliper.sh
