- hosts: client
  become: yes
  gather_facts: no
  tasks:
  
  - name: install packages
    package: 
      name:
        - make
        - iperf
        - golang-go
        - nodejs 
        - npm
      state: present
      
  - npm:
      name: "{{item}}"
      global: yes
    with_items:
      - "node-gyp"
      - "npx"
      
  - shell: npm install -g --only=prod @hyperledger/caliper-cli@0.3.0
  
  - shell: npm install -g npm@latest --no-optional
  
  - shell: caliper bind --caliper-bind-sut fabric --caliper-bind-sdk 1.4.4 --caliper-bind-cwd ./
  
  
#   - name: Download 
#     get_url:
#       url: https://raw.githubusercontent.com/QCDIS/blockchain_deplyment/master/install-caliper.sh
#       dest: /tmp/install-caliper.sh
#       mode: '777'
  
#   - name: install 
#     shell: bash /tmp/install-caliper.sh
