---
- hosts: client
  become: yes
  gather_facts: no
  tasks:
  
    - git:
        repo: "{{config_repo_url}}"
        dest: /tmp/conf
        version: "{{release}}"
        force: yes
    
#     - shell: curl -sSL http://bit.ly/2ysbOFE | bash -s -- 1.4.1 1.4.1 0.4.15 -ds
    - shell: cd /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/ && /tmp/conf/caliper-benchmarks/bin/cryptogen generate --config=/tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/crypto-config.yaml
    - shell: cd /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/ && /tmp/conf/caliper-benchmarks/bin/configtxgen -profile OrdererGenesis -outputBlock genesis.block -channelID syschannel
    - shell: cd /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/ && /tmp/conf/caliper-benchmarks/bin/configtxgen -profile ChannelConfig -outputCreateChannelTx mychannel.tx -channelID mychannel


#     - archive:
#         path: /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/crypto-config
#         dest: /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/config/crypto-config.zip
    
        
    - fetch:
        src: /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/config/{{item}}
        dest: /tmp/
      with_items:
        - "crypto-config.yaml"
        - "genesis.block"
        - "mychannel.tx"
      register: fetch_output
            
     

- hosts: workers
  become: yes
  gather_facts: no
  tasks:
  
    - ansible.builtin.file:
        path: /tmp/conf
        state: directory
        
        
    - copy:
        src: /tmp/client/tmp/conf/networks/fabric/fabric-v1.4.1/config/"{{item}}"
        dest: /tmp/conf
      with_items:
        - "crypto-config.yaml"
        - "genesis.block"
        - "mychannel.tx"
        


    

    
        
