---
- hosts: client
  become: yes
  gather_facts: no
  tasks:
  
    - git:
        repo: "{{config_repo_url}}"
        dest: /tmp/conf
        version: "{{release}}"
        force: yes
    
#     - shell: curl -sSL http://bit.ly/2ysbOFE | bash -s -- 1.4.1 1.4.1 0.4.15 -ds
    - shell: cd /tmp/conf/networks/fabric/fabric-v1.4.1/config/ && /tmp/conf/bin/cryptogen generate --config=/tmp/conf/networks/fabric/fabric-v1.4.1/config/crypto-config.yaml
    - shell: cd /tmp/conf/networks/fabric/fabric-v1.4.1/config/ && /tmp/conf/bin/configtxgen -profile OrdererGenesis -outputBlock genesis.block -channelID syschannel
    - shell: cd /tmp/conf/networks/fabric/fabric-v1.4.1/config/ && /tmp/conf/bin/configtxgen -profile ChannelConfig -outputCreateChannelTx mychannel.tx -channelID mychannel

         
         
    - archive:
        path: /tmp/conf
        dest: /tmp/conf.zip
        
    - fetch:
         src: /tmp/conf.zip
         dest: /tmp
     

- hosts: workers
  become: yes
  gather_facts: no
  tasks:
  
    - copy:
        src: /tmp/conf.zip
        dest: /tmp
        
