---
- hosts: client
  become: yes
  gather_facts: no
  vars:
    conf_path: /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config
  tasks:
  
    - git:
        repo: "{{config_repo_url}}"
        dest: /tmp/conf
        version: "{{release}}"
        force: yes
            
    - shell: cd "{{conf_path}}" && /tmp/conf/caliper-benchmarks/bin/cryptogen generate --config="{{conf_path}}"/crypto-config.yaml
    - shell: cd "{{conf_path}}" && /tmp/conf/caliper-benchmarks/bin/configtxgen -profile OrdererGenesis -outputBlock genesis.block -channelID syschannel
    - shell: cd "{{conf_path}}" && /tmp/conf/caliper-benchmarks/bin/configtxgen -profile ChannelConfig -outputCreateChannelTx mychannel.tx -channelID mychannel

    - find:
        paths: "/tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/crypto-config/"
        patterns: '*_sk'
        recurse: yes
      register: certs
            
    - copy: 
        remote_src: yes
        src: "{{ item.path }}"
        dest: "{{ item.path | dirname}}/key.pem"
        
    - fetch:
        src: "{{conf_path}}/{{item}}"
        dest: /tmp/
      with_items:
        - "crypto-config.yaml"
        - "genesis.block"
        - "mychannel.tx"
      register: fetch_output
            
     

- hosts: workers
  become: yes
  gather_facts: no
  vars:
    conf_path: /tmp/conf/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config
  tasks:
  
    - ansible.builtin.file:
        path: /tmp/conf
        state: directory
        
        
    - copy:
        src: "/tmp/client/{{conf_path}}/{{item}}"
        dest: /tmp/conf
      with_items:
        - "crypto-config.yaml"
        - "genesis.block"
        - "mychannel.tx"
        


    

    
        
