- hosts: client
  become: yes
  gather_facts: no
  tasks:    

    - docker_network:
        name: caliper-overlay 
        driver: overlay 
        

    - docker_stack:
        state: present
        name: prometheus
        compose:
          - /tmp/conf/monitor/swarm-compose.yaml
  
    - name: Test 
      shell: caliper benchmark run --caliper-benchconfig /tmp/conf/fabric/config.yaml --caliper-networkconfig /tmp/conf/fabric/networks/fabric.yaml --caliper-workspace .
