- hosts: all
  become: yes
  gather_facts: no
  tasks:
  
  - apt:
      upgrade: yes
      update_cache: yes
      autoremove: yes
      autoclean: yes
    
  
  - name: install packages
    package: 
      name:
        - stress
        - iperf
        - golang-go
        - nodejs 
        - npm
      state: present

  - include: docker/install_docker.yaml
  
  - include: install_hyperledger.yaml
    
    
#   - name: Download install.sh
#     get_url:
#       url: https://raw.githubusercontent.com/QCDIS/blockchain_deplyment/master/install.sh
#       dest: /tmp/install.sh
#       mode: '777'
  
#   - name: install 
#     shell: bash /tmp/install.sh
